apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: mosquitto
spec:
  type: ClusterIP
  ports:
  - port: 1883
    targetPort: 1883
    name: mqtt
  - port: 8883
    targetPort: 8883
    name: mqttssl
  - port: 9001
    targetPort: 9001
    name: ws
  selector:
    app: broker
  externalIPs: ["116.202.187.121"]